export const COACHES = [
  'Chui Ling Villafuerte Goh', 'Xavier Bertril Nuico Cuerpo', 'Gazelle Broniola Bulalacao', 
  'Zaira Mae Regino Kinol', 'Charbel Rado Mahinay', 'Karl Jasper Lorejo Mag-usara', 
  'Erwin Verano', 'Kyla Serion', 'May-Ann Alabata Montegrejo', 'Ma. Mikaela Lalamonan Barrera', 
  'Joe Mari Torda Piñero', 'John Rey Aspacio Ortega', 'Korina Kim Romeo Alcantara', 
  'Elaine De Leon Roxas', 'Irene Villarin Estravela', 'Shanne Juliet Credo Diputado', 
  'Maria Fatima Serrano Buenviaje', 'Alyssa Sandel Reyes', 'Joenesse Vhem Laraya Bonghanoy', 
  'Krishia May Capuyan Saldivar'
];

export const AGENTS = [
  'Abegail Lariosa Ingco', 'Aiva Paquira Abalos', 'Alina Amaya Zelaya', 'Alvin Cajipo Saguban', 
  'Alvin Portallo Gemira', 'Alyanna Juhl Soledad Aquino', 'Angel Reyes Guarin', 'Ann Kimberly Vidal Ablir', 
  'Anne June Mariño Dumaldal', 'Arcelie Macatunog Patula', 'Archie Ferrolino Osa', 'Argie Dialino Cayetano', 
  'Ariane Mae Tercio Ib-Ib', 'Arlita Trinidad Calingacion', 'Arzy Llemit', 'Ashley Barrera Adalid', 
  'Bello Isah Egano Habibulla', 'Belmarie Manggon Zamora', 'Cesar Joseph Hernandez Unabia', 
  'Charlyn Acabal Cambio', 'Chiran Solamillo Tortogo Jr.', 'Christin Sanchez', 
  'Christine Gywneth Naval Estomagulang', 'Christofer Dumaran Perocho', 'Clint Ybonne Ronato Anadon', 
  'Cris-Ann Ruado Relox', 'Crystal Jycel Longno Beron', 'Cyril Brondial Santos', 'Darwin Levin Lope Data', 
  'Daryll Tulod Bentulan', 'Daven Paul Manlupig Dorimon', 'Devielyn Kaye Diola Trangia', 
  'Dexter Dumaog Japay', 'Diana Sojor Solibio', 'Dinalyn Macasinag Villalon', 'Dino Amiel Lojo Balaga', 
  'Dominique Eurika Portada Katada', 'Donna Amores', 'Drea Timonan Surbito', 'Dwaynee Chan Benignos', 
  'Edeson Alabata Abo-Abo', 'Edwin Zabala Dizon', 'Elenie Villaro Tito', 'Emiliano Alexie Casaje San Pedro Jr.', 
  'Eva Mae Gerardo Violeta', 'Farah Mae Lope Torres', 'Felori Baguihon Siplao', 'Flora May Carcusia Cagampang', 
  'Frances Bryle Millan Gelvoria', 'Francose Marie Partosa Estrada', 'Genilyn Bautista Aseñas', 
  'Gina Panaligan Bautista', 'Haissam Rohann Bocanegra Morton', 'Heinz Harald Pagon Acson', 
  'Honey Ege Radoc', 'Honeylen Landisa', 'Irene Ann Cadallo Bahandi', 'Irene Dagoy Rolandong', 
  'Iris Mae Recaldo Timbal', 'Ivan Allan Bungcasan', 'Jade Marian Daarol Gabunilas', 
  'Jamaica Arranchado Veriña', 'James Saycon Buagas', 'Jan August Delfin Villamor', 
  'Jana Esperanza Sun Dalleda', 'Jared Xavierre Giron Manuel', 'Jay Mark Almonte Tuayon', 
  'Jayrilyn Devero Alberto', 'Jayson Saycon Caminos', 'Jeff Cantina Dela Cruz', 'Jefford Lu-Ang Algoso', 
  'Jeizel Eringe Mapula', 'Jeniefe Tubac Garcia', 'Jenifer Alatan Balanay', 'Jerald Anqui Olasiman', 
  'Jeremy Capalad Albina', 'Jeremy Ruso Arnaiz', 'Jerome Makasilhig Olarte', 'Jesmar Borromeo Maxino', 
  'Jessa Dee Silva Romero', 'Jessa Galve Amparado', 'Jessa Kadusale Casido', 'Jesselaine Hinaut Siglos', 
  'Jessica Causing Montecillo', 'Jessica Cuizon Catubig', 'Jessuelle Zaira Patrimonio', 
  'Jimboy Tortusa Corciega', 'Joan Catinggan', 'Joann Torres Balasabas', 'Johann Pabayos Aran', 
  'John Christopher Ang Tismo', 'John Patrick Gutierrez Diaz', 'John Paul Jabas Romano', 
  'John Philip Bulagao', 'John Ric Carabaña Vallejos', 'Johnnas Vidanes Morales', 'Jolina Tinaytina Lopez', 
  'Joriel Duran Elloren', 'Jose Louise Varona Anda', 'Jose Yael Inocente', 'Josephine Belaro Olbes', 
  'Jostuart Stanley Monsole Gunter', 'June Solamillo Lucilla', 'Karl Elmer Ii Cavite Piamonte', 
  'Karla Louise Claud Ramos', 'Kay Ann Apurado Quio', 'Kevin Berino Elumba', 'Kimberly Anne Siquijor Garol', 
  'Kimberly Nicole Lim Cachero', 'Kristine Garcia Ramos', 'Kyla Saracia Abalos', 'Kylle Elaine Econg Manninen', 
  'Lenie Jane Tarog', 'Lourdes Apple Calidguid Unajan', 'Luther Maglinte Dalura', 'Ma Reynaline Canseco Barona', 
  'Mae Jumawan Sasil', 'Maevel Cruz Umalza', 'Maricel Morquida', 'Marichu Bornillo Acar', 
  'Marion Jean Espero Vital', 'Marites Taburnal Agustin', 'Marlo Villarin Labrador', 
  'Marry Jen Villieta Catubig', 'Marth Joseph Dayao Enopia', 'Mary Caribelle Anne Miculob', 
  'Mary Vella Paltinca', 'Meguela Angela Bisco Dagoy', 'Melissa Tan Capulong', 'Merbelyn Magbanua Mancia', 
  'Michael Angelo Bisabis Taub', 'Michelle Guzman Plazos', 'Michelle Zamora Ortiz', 
  'Mickel Arvin Lloyd Noay', 'Mitch Vianca Ferenal Bajenting', 'Neil Brent Norico Barte', 
  'Nhova Kristy Catubig Venenoso', 'Nica Diona Algadepe Segara', 'Niño Kim Daniel Frutas Legaspi', 
  'Noel John Callao Canoy', 'Oliver Jr Gilhang Soriano', 'Paul Vincent Dispe Valerio', 
  'Precious Jewel Salazar', 'Princess Shaine Mimis Asidera', 'Rey Eufronio Laguitao Buagas', 
  'Reynold Abejero Mariño', 'Reza Lindayao Lumjod', 'Riza Venales Kilapkilap', 'Rizza Jean Fernandez', 
  'Rolando Busbus Daohog', 'Rona May Beatingo Astillar', 'Rose Ann Laque Bangcat', 
  'Rosean Mae Valencia Lambayan', 'Roselyn Montecino Laure', 'Rosenia Nieves', 'Roxy Salveron Maquiling', 
  'Ryan Amoma Vios', 'Sajilli Renz Balucan Bacallo', 'Sandae Manaban Placer', 'Sanny Boy Erot Duran', 
  'Shan Mae Ragpa Gajegan', 'Shazia Jamil Pirzada', 'Sheena Estoconing Bugais', 'Shelamae Cadiz Bohol', 
  'Shella Mae Legarde Cagatin', 'Sky Sagario Gravador', 'Sylysdley Lasola Gutierrez', 
  'Thelma Evangelista Laurena', 'Trisha Mae Abayao Bianado', 'Valerie Ann Trasona Delicano', 
  'Vica Kay Esoy Verden', 'Victor Iligan Liu', 'Vincent Cafino Banlat', 'Vincent Jonas Gallendo', 
  'Vincent Paul Villa Malagar', 'Wilma Gaso Rodriguez', 'Wisdom K Patron Alama', 'Xyza Rae Alipio'
];
