/**
 * Standardizes names from short/tool versions to official full names.
 * These mappings convert shorthand/nicknames found in the spreadsheet to official database records.
 */
export const NAME_MAPPINGS: Record<string, string> = {
  "Melissa Capulong": "Melissa Tan Capulong",
  "Alliah Aliaviado": "Alliah Josah Ganosa Aliviado",
  "Karl Piamonte": "Karl Elmer II Cavite Piamonte",
  "Josephine Olbes": "Josephine Belaro Olbes",
  "Kylle Manninen": "Kylle Elaine Econg Manninen",
  "Christine Estomagulang": "Christine Gywneth Naval Estomagulang",
  "Rose Bangcat": "Rose Ann Laque Bangcat",
  "Sandae Placer": "Sandae Manaban Placer",
  "Shanne Diputado": "Shanne Juliet Credo Diputado",
  "Christin Sanchez": "Christin Sanchez",
  "Elenie Tito": "Elenie Villaro Tito",
  "Jerald Olasiman": "Jerald Anqui Olasiman",
  "Joann Balasabas": "Joann Torres Balasabas",
  "Marites Agustin": "Marites Taburnal Agustin",
  "Alina Amaya": "Alina Amaya Zelaya",
  "Meguela Dagoy": "Meguela Angela Bisco Dagoy",
  "Jessica Catubig": "Jessica Cuizon Catubig",
  "Shelamae Bohol": "Shelamae Cadiz Bohol",
  "Roxy Maquiling": "Roxy Salveron Maquiling",
  "Alexie San Pedro": "Emiliano Alexie Casaje San Pedro Jr.",
  "Jay Tuayon": "Jay Mark Almonte Tuayon",
  "Kristine Ramos": "Kristine Garcia Ramos",
  "Charlyn Cambio": "Charlyn Acabal Cambio",
  "Ej Samson": "Ej Gabrielle Samson Fua",
  "Haissam Morton": "Haissam Rohann Bocanegra Morton",
  "Joan Catinggan": "Joan Catinggan",
  "Rosean Lambayan": "Rosean Mae Valencia Lambayan",
  "Reynold Mariño": "Reynold Abejero Mariño",
  "Reza Lumjod": "Reza Lindayao Lumjod",
  "Sheena Bugais": "Sheena Estoconing Bugais",
  "Kharl Teves": "Kharl Devero Teves",
  "Trisha Bianado": "Trisha Mae Abayao Bianado",
  "Jessa Amparado": "Jessa Galve Amparado",
  "Lenie Tarog": "Lenie Jane Tarog",
  "Shan Gajegan": "Shan Mae Ragpa Gajegan",
  "Dinalyn Villalon": "Dinalyn Macasinag Villalon",
  "Dwaynee Benignos": "Dwaynee Chan Benignos",
  "Iris Timbal": "Iris Mae Recaldo Timbal",
  "Jerome Olarte": "Jerome Makasilhig Olarte",
  "Francose Estrada": "Francose Marie Partosa Estrada",
  "Precious Salazar": "Precious Jewel Salazar",
  "Vica Verden": "Vica Kay Esoy Verden",
  "Alvin Saguban": "Alvin Cajipo Saguban",
  "Ashley Adalid": "Ashley Barrera Adalid",
  "Darwin Data": "Darwin Levin Lope Data",
  "Kyla Abalos": "Kyla Saracia Abalos",
  "Luther Dalura": "Luther Maglinte Dalura",
  "Edeson Abo-Abo": "Edeson Alabata Abo-abo",
  "Honeylen Landisa": "Honeylen Landisa",
  "Jeremy Albina": "Jeremy Capalad Albina",
  "Crystal Beron": "Crystal Jycel Longno Beron",
  "Jessica Montecillo": "Jessica Causing Montecillo",
  "John Bulagao": "John Philip Bulagao",
  "Sky Gravador": "Sky Sagario Gravador",
  "Oliver Soriano": "Oliver Jr Gilhang Soriano",
  "Clint Anadon": "Clint Ybonne Ronato Anadon",
  "CrisAnn Relox": "Cris-Ann Ruado Relox",
  "June Lucilla": "June Solamillo Lucilla",
  "Valerie Delicano": "Valerie Ann Trasona Delicano",
  "Archie Osa": "Archie Ferrolino Osa",
  "Raymart Maglente": "Raymart Tumabing Maglente",
  "Jessuelle Patrimonio": "Jessuelle Zaira Patrimonio",
  "Shazia Pirzada": "Shazia Jamil Pirzada",
  "Cynthia Nesnia": "Cynthia Mae Manatad Nesnia",
  "Edwin Dizon": "Edwin Zabala Dizon",
  "Jade Gabunilas": "Jade Marian Daarol Gabunilas",
  "Jefford Algoso": "Jefford Lu-ang Algoso",
  "Jeremy Arnaiz": "Jeremy Ruso Arnaiz",
  "Jose Inocente": "Jose Yael Inocente",
  "Kimberly Garol": "Kimberly Anne Siquijor Garol",
  "Sajilli Bacallo": "Sajilli Renz Balucan Bacallo",
  "Genilyn Aseñas": "Genilyn Bautista Aseñas",
  "Pearl Tumilap": "Pearl Pajares Tumilap",
  "Anne Dumaldal": "Anne June Mariño Dumaldal",
  "Mary Paltinca": "Mary Vella Paltinca",
  "Xyza Alipio": "Xyza Rae Alipio",
  "Irene Bahandi": "Irene Ann Cadallo Bahandi",
  "Jimboy Corciega": "Jimboy Tortusa Corciega",
  "Jolina Lopez": "Jolina Tinaytina Lopez",
  "John Romano": "John Paul Jabas Romano",
  "Victor Liu": "Victor Iligan Liu",
  "Ivan Bungcasan": "Ivan Allan Bungcasan",
  "Jopel Ybañez": "Jopel Erojo Ybañez",
  "Christopher Tagnipis": "Christopher Bilocura Tagnipis",
  "Donna Amores": "Donna Amores",
  "Djamaicca Alama": "Djamaicca Quinol Alama",
  "Heinz Acson": "Heinz Harald Pagon Acson",
  "Paul Valerio": "Paul Vincent Dispe Valerio",
  "Jana Dalleda": "Jana Esperanza Sun Dalleda",
  "Jostuart Gunter": "Jostuart Stanley Monsole Gunter",
  "Vincent Gallendo": "Vincent Jonas Gallendo",
  "Vincent Banlat": "Vincent Cafino Banlat",
  "Jesselaine Siglos": "Jesselaine Hinaut Siglos",
  "Ariane Ib-Ib": "Ariane Mae Tercio Ib-ib",
  "Joriel Elloren": "Joriel Duran Elloren",
  "Jenifer Balanay": "Jenifer Alatan Balanay",
  "Nica Segara": "Nica Diona Algadepe Segara",
  "Noel Canoy": "Noel John Callao Canoy",
  "Riza Kilapkilap": "Riza Venales Kilapkilap",
  "Kevin Elumba": "Kevin Berino Elumba",
  "Marth Enopia": "Marth Joseph Dayao Enopia",
  "Karla Ramos": "Karla Louise Claud Ramos",
  "Marlo Labrador": "Marlo Villarin Labrador",
  "Jayrilyn Alberto": "Jayrilyn Devero Alberto",
  "Jayson Caminos": "Jayson Saycon Caminos",
  "Flora Cagampang": "Flora May Carcusia Cagampang",
  "Gina Bautista": "Gina Panaligan Bautista",
  "Nhova Venenoso": "Nhova Kristy Catubig Venenoso",
  "Merbelyn Mancia": "Merbelyn Magbanua Mancia",
  "Ann Ablir": "Ann Kimberly Vidal Ablir",
  "Roselyn Laure": "Roselyn Montecino Laure",
  "Abegail Ingco": "Abegail Lariosa Ingco",
  "Marichu Acar": "Marichu Bornillo Acar",
  "John Vallejos": "John Ric Carabaña Vallejos",
  "Wilma Rodriguez": "Wilma Gaso Rodriguez",
  "Lourdes Unajan": "Lourdes Apple Calidguid Unajan",
  "Jeizel Mapula": "Jeizel Eringe Mapula",
  "Sanny Duran": "SANNY BOY EROT DURAN",
  "Christofer Perocho": "Christofer Dumaran Perocho",
  "Thelma Laurena": "Thelma Evangelista Laurena",
  "Diana Solibio": "Diana Sojor Solibio",
  "Jessa Casido": "Jessa Kadusale Casido",
  "Alyanna Aquino": "Alyanna Juhl Soledad Aquino",
  "Eva Violeta": "Eva Mae Gerardo Violeta",
  "John Tismo": "John Christopher Ang Tismo",
  "Mickel Noay": "Mickel Arvin Lloyd Noay",
  "Rey Buagas": "Rey Eufronio Laguitao Buagas",
  "Mae Sasil": "Mae Jumawan Sasil",
  "Drea Surbito": "Drea Timonan Surbito",
  "Kay Quio": "Kay Ann Apurado Quio",
  "Reynaline Barona": "Ma Reynaline Canseco Barona",
  "Belmarie Zamora": "Belmarie Manggon Zamora",
  "Jose Anda": "Jose Louise Varona Anda",
  "Argie Cayetano": "Argie Dialino Cayetano",
  "Johann Aran": "Johann Pabayos Aran",
  "Wisdom Alama": "Wisdom K Patron Alama",
  "Maevel Umalza": "Maevel Cruz Umalza",
  "Angel Guarin": "Angel Reyes Guarin",
  "Mary Ragudo": "Mary Joy Ewayan Ragudo",
  "Neil Barte": "Neil Brent Norico Barte",
  "Rona Astillar": "Rona May Beatingo Astillar",
  "James Buagas": "James Saycon Buagas",
  "Alvin Gemira": "Alvin Portallo Gemira",
  "Dexter Japay": "Dexter Dumaog Japay",
  "Honey Radoc": "Honey Ege Radoc",
  "Arzy Llemit": "Arzy Llemit",
  "Felori Siplao": "Felori Baguihon Siplao",
  "Ryan Vios": "Ryan Amoma Vios",
  "John Diaz": "John Patrick Gutierrez Diaz",
  "Mary Miculob": "Mary Caribelle Anne Miculob",
  "Rizza Fernandez": "Rizza Jean Fernandez",
  "Rosenia Nieves": "Rosenia Nieves",
  "Nino Legaspi": "Niño Kim Daniel Frutas Legaspi",
  "Arlita Calingacion": "Arlita Trinidad Calingacion",
  "Devielyn Trangia": "Devielyn Kaye Diola Trangia",
  "Sylysdley Gutierrez": "Sylysdley Lasola Gutierrez",
  "Farah Torres": "Farah Mae Lope Torres",
  "Jan Villamor": "Jan August Delfin Villamor",
  "Shella Cagatin": "Shella Mae Legarde Cagatin",
  "Frances Gelvoria": "Frances Bryle Millan Gelvoria",
  "Lyndel Verzano": "Lyndel Mae Baguio Verzano",
  "Irene Rolandong": "Irene Dagoy Rolandong",
  "Diditz Informanes": "Diditz Grace Roda Informanes",
  "Rolando Daohog": "Rolando Busbus Daohog",
  "Edmar Baylon": "Edmar Muyco Baylon",
  "Johnnas Morales": "Johnnas Vidanes Morales",
  "Princess Asidera": "Princess Shaine Mimis Asidera",
  "Daven Dorimon": "Daven Paul Manlupig Dorimon",
  "Cyril Santos": "Cyril Brondial Santos",
  "Cesar Unabia": "Cesar Joseph Hernandez Unabia",
  "Michelle Plazos": "Michelle Guzman Plazos",
  "Vincent Malagar": "Vincent Paul Villa Malagar",
  "Bello Habibulla": "Bello Isah Egano Habibulla",
  "Arcelie Patula": "Arcelie Macatunog Patula",
  "Michael Taub": "Michael Angelo Bisabis Taub",
  "Aiva Abalos": "Aiva Paquira Abalos",
  "Marion Vital": "MARION JEAN ESPERO VITAL",
  "Kimberly Cachero": "Kimberly Nicole Lim Cachero",
  "Chiran Tortogo": "Chiran Solamillo Tortogo Jr.",
  "Jared Manuel": "Jared Xavierre Giron Manuel",
  "Jeff Dela Cruz": "Jeff Cantina Dela Cruz",
  "Dominique Katada": "Dominique Eurika Portada Katada",
  "Jessa Romero": "Jessa Dee Silva Romero",
  "Michelle Ortiz": "Michelle Zamora Ortiz",
  "Jesmar Maxino": "Jesmar Borromeo Maxino",
  "Daryll Bentulan": "Daryll Tulod Bentulan",
  "Dino Balaga": "Dino Amiel Lojo Balaga",
  "Jamaica Veriña": "Jamaica Arranchado Veriña",
  "Mitch Bajenting": "Mitch Vianca Ferenal Bajenting",
  "Maricel Morquida": "Maricel Morquida",
  "Marry Jen Catubig": "Marry Jen Villieta Catubig",
  "Jeniefe Garcia": "Jeniefe Tubac Garcia",
  // Handlers for some specific variants reported earlier
  "Jimgirl Corciega": "Jimboy Tortusa Corciega",
  "Erwin Verano": "Erwin Verano",
  "Felrose Magalso": "Felrose Quisel Magalso",
  "Crisann Relox": "Cris-Ann Ruado Relox",
};

/**
 * Normalizes a name by stripping leading @ and checking against mappings.
 */
export function normalizeName(name: string): string {
  if (!name) return "";
  let trimmed = name.trim();
  
  // Standardize case-insensitive and handle @ signs
  if (trimmed.startsWith('@')) {
    trimmed = trimmed.substring(1).trim();
  }

  // Check mapping (case-sensitive check first for speed)
  if (NAME_MAPPINGS[trimmed]) return NAME_MAPPINGS[trimmed];

  // Case-insensitive fallback
  const lowerTrimmed = trimmed.toLowerCase();
  for (const [nickname, fullName] of Object.entries(NAME_MAPPINGS)) {
    if (nickname.toLowerCase() === lowerTrimmed) return fullName;
  }

  return trimmed;
}
